/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 42
#define YY_END_OF_BUFFER 43
static yyconst short int yy_acclist[234] =
    {   0,
       43,   41,   42,    3,   41,   42,    1,   42,   41,   42,
        2,   41,   42,   32,   41,   42,   33,   41,   42,   30,
       41,   42,   27,   41,   42,   41,   42,   31,   41,   42,
       31,   41,   42,   31,   41,   42,   39,   41,   42,   29,
       41,   42,   29,   41,   42,   34,   41,   42,   35,   41,
       42,   29,   41,   42,   29,   41,   42,   29,   41,   42,
       29,   41,   42,   29,   41,   42,   29,   41,   42,   29,
       41,   42,   29,   41,   42,   36,   41,   42,   40,   41,
       42,   37,   41,   42,   41,   42,    1,   31,    2,   27,
       26,   29,   29,   29,   29,   29,   29,   29,   29,   29,

       29,   29,   29,   29,   29,   29,   29,   38,   28,   29,
       29,   29,    9,   29,   11,   29,   13,   29,   29,   29,
       29,   29,   29,   29,   12,   29,    8,   29,   10,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   19,   29,   18,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   15,   29,   16,   29,
       29,   29,   29,   29,    6,   29,   29,   29,   29,   29,
        7,   29,   29,   29,   14,   29,   29,    5,   29,   17,
       29,    4,   29,   29,   29,   29,   29,   29,   24,   29,

       29,   29,   29,   29,   25,   29,   29,   29,   29,   29,
       22,   29,   23,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   21,   29,   29,   29,   29,   29,
       29,   20,   29
    } ;

static yyconst short int yy_accept[162] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   11,   14,   17,
       20,   23,   26,   28,   31,   34,   37,   40,   43,   46,
       49,   52,   55,   58,   61,   64,   67,   70,   73,   76,
       79,   82,   85,   87,   88,   89,   90,   90,   91,   92,
       93,   94,   95,   96,   97,   98,   99,  100,  101,  102,
      103,  104,  105,  106,  107,  108,  109,  110,  111,  112,
      113,  115,  117,  119,  120,  121,  122,  123,  124,  125,
      127,  129,  131,  132,  133,  134,  135,  136,  137,  138,
      139,  140,  141,  142,  143,  144,  145,  146,  147,  148,
      149,  150,  151,  152,  153,  154,  155,  157,  159,  160,

      161,  162,  163,  164,  165,  166,  167,  169,  171,  172,
      173,  174,  175,  177,  178,  179,  180,  181,  183,  184,
      185,  187,  188,  190,  192,  194,  195,  196,  197,  198,
      199,  201,  202,  203,  204,  205,  207,  208,  209,  210,
      211,  213,  215,  216,  217,  218,  219,  220,  221,  222,
      223,  224,  225,  227,  228,  229,  230,  231,  232,  234,
      234
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    1,    5,    1,    1,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   22,   22,   24,   22,
       22,   22,   22,   22,   22,   25,   26,   22,   22,   22,
       22,   27,   22,   28,   29,   30,   22,   22,   22,   22,
       31,    1,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   22,   40,   22,   41,   42,   22,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   53,   22,   54,
       22,   22,   55,   56,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       58,    1,    1,   59,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[60] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    1,    1,    3,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[164] =
    {   0,
        0,    0,   98,  724,  724,   90,   73,    0,  724,  724,
      724,   48,   71,   69,  724,   67,  724,   50,   52,  724,
      724,   54,   56,   60,   62,   67,   81,   96,  100,  724,
      724,  724,   25,   79,  724,    0,   66,   63,  724,    0,
      107,  112,  113,  118,  122,  124,  126,  143,  128,  150,
      156,  168,  162,  169,  175,  724,   65,  181,  183,  187,
      197,  202,  208,  219,  218,  223,  224,  234,  236,  240,
      245,  250,  251,  258,  267,  262,  272,  276,  277,  288,
      284,  298,  303,  293,  314,  315,  332,  336,  343,  348,
      350,  358,  354,  362,  367,  369,  375,  376,  388,  393,

      402,  403,  407,  418,  424,  414,  428,  432,  433,  440,
      446,  454,  458,  459,  465,  472,  484,  486,  490,  498,
      502,  503,  511,  512,  516,  517,  527,  528,  529,  538,
      543,  544,  556,  557,  570,  571,  575,  583,  584,  589,
      597,  599,  601,  605,  610,  611,  623,  629,  627,  636,
      651,  653,  655,  660,  662,  666,  668,  670,  672,  724,
      720,   69,   66
    } ;

static yyconst short int yy_def[164] =
    {   0,
      160,    1,  160,  160,  160,  160,  160,  161,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  162,  162,  160,
      160,  162,  162,  162,  162,  162,  162,  162,  162,  160,
      160,  160,  160,  160,  160,  161,  160,  160,  160,  163,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  160,  160,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,

      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,    0,
      160,  160,  160
    } ;

static yyconst short int yy_nxt[784] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   11,   11,
       11,    4,   11,   12,   13,   11,   14,   15,   16,   17,
       11,   18,   18,   18,   18,   18,   18,   18,   19,   18,
       20,   21,   11,    4,   18,   22,   23,   18,   18,   24,
       18,   18,   18,   25,   26,   18,   18,   18,   18,   27,
       28,   18,   29,   18,   30,   31,   32,    4,   33,   37,
       40,   38,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   41,   40,   40,   37,   40,   38,   40,   57,   57,
       40,   34,   56,   40,   35,   40,   35,   40,   39,   40,
       35,   40,   34,   40,   40,   40,   42,  160,   46,  160,

       40,   44,   47,   43,   49,   45,   40,   50,  160,   40,
       40,   48,  160,   40,   40,   51,  160,   40,  160,   52,
       40,   53,   40,   40,  160,   40,   40,  160,   40,   40,
       54,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,  160,  160,  160,   40,   40,   59,  160,   55,
      160,   40,   58,   40,  160,   40,   40,   40,   63,   40,
       40,   40,   60,   40,   65,  160,   40,   61,   62,   40,
      160,  160,   40,   67,   64,   40,   40,   66,   40,   40,
      160,   40,   40,   40,  160,   40,  160,   68,   40,   40,
      160,   40,  160,   40,   40,   40,   40,   40,   69,  160,

       40,   40,   40,  160,   70,  160,   71,   40,   40,   73,
       40,  160,   40,   72,   40,   40,   40,  160,   40,  160,
       40,   40,  160,   76,   77,   75,   74,  160,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,  160,  160,
      160,   40,   78,   79,   40,   80,   40,   40,  160,   40,
       40,   40,   40,   40,  160,   40,   40,   40,   40,  160,
       40,   40,   81,   40,   40,   82,  160,   40,   40,   40,
      160,   40,   40,   40,   83,   40,   85,   40,   40,   84,
       40,  160,   40,   40,   40,   40,   40,   40,  160,   40,
       40,   40,  160,   86,   40,   40,   89,   40,   40,  160,

       40,   40,   87,   40,  160,   40,   40,   88,   40,   40,
       40,   40,   90,   40,  160,  160,   40,   40,  160,  160,
      160,   40,   92,  160,   40,   40,   40,   40,   40,   91,
      160,   40,  160,   93,   94,  160,   40,  160,   95,  160,
       96,  160,   40,   98,   97,   40,   40,   40,   40,   40,
      160,   99,  160,   40,  101,  100,   40,  102,   40,  103,
       40,   40,  160,   40,   40,   40,  160,   40,   40,   40,
      160,   40,   40,  104,  160,   40,   40,   40,  160,   40,
       40,   40,   40,   40,  106,   40,   40,   40,   40,   40,
      160,   40,  160,  105,  160,   40,  107,  108,   40,  109,

       40,   40,   40,   40,  111,  160,   40,  160,   40,   40,
      110,  160,   40,   40,  112,   40,   40,   40,  160,  160,
       40,   40,  113,  160,   40,  160,   40,   40,   40,  160,
      114,   40,  160,  160,   40,   40,   40,   40,   40,  160,
       40,   40,   40,   40,  115,   40,   40,   40,  116,  160,
       40,   40,  118,   40,  120,  117,   40,   40,  160,   40,
      160,   40,  119,  160,   40,   40,   40,   40,   40,   40,
      160,   40,   40,   40,  122,   40,  160,  160,   40,   40,
      123,  160,   40,  121,  160,   40,  160,   40,  160,  160,
      160,   40,   40,  125,   40,  160,   40,   40,   40,   40,

       40,  160,  160,   40,  124,   40,  160,  160,   40,  127,
      126,   40,   40,   40,  160,   40,   40,   40,  128,   40,
      160,   40,   40,   40,   40,   40,   40,   40,  160,   40,
       40,   40,  160,  160,  129,   40,   40,   40,   40,   40,
       40,   40,   40,  130,   40,   40,  160,  160,   40,   40,
       40,   40,  131,   40,   40,  160,   40,   40,  160,  160,
       40,   40,   40,  135,  132,  133,   40,   40,  160,   40,
       40,   40,  160,  160,  160,  160,   40,   40,  134,  160,
       40,   40,  136,   40,   40,   40,  160,  160,   40,   40,
       40,  139,  160,   40,   40,  137,   40,   40,  138,   40,

      160,  160,   40,   40,   40,  160,  140,   40,   40,   40,
       40,   40,   40,  141,   40,   40,   40,   40,   40,  160,
       40,   40,   40,   40,   40,  160,  160,  143,  142,  144,
       40,  160,   40,   40,   40,  160,   40,   40,   40,   40,
       40,  145,   40,   40,   40,  160,   40,  160,  147,   40,
      146,  160,  160,  160,  160,  148,   40,  160,  150,  160,
       40,   40,   40,   40,   40,   40,   40,  149,   40,   40,
       40,  160,   40,   40,  152,   40,   40,  151,   40,   40,
       40,   40,   40,   40,   40,   40,   40,  160,   40,  154,
      160,  160,  160,   40,  160,   40,  153,  160,  160,   40,

      160,   40,  160,   40,  160,   40,  158,  156,  160,  160,
      155,  160,  160,  160,  157,  160,  160,  160,  160,  159,
       36,  160,   36,    3,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160
    } ;

static yyconst short int yy_chk[784] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   12,
       18,   12,   19,   18,   22,   19,   23,   22,  163,   23,
       24,  162,   25,   24,   38,   25,   38,   26,   57,   37,
       26,   34,   33,   18,   16,   19,   14,   22,   13,   23,
        7,   27,    6,   24,   27,   25,   19,    3,   24,    0,

       26,   23,   25,   22,   26,   23,   28,   26,    0,   28,
       29,   25,    0,   29,   27,   27,    0,   41,    0,   27,
       41,   27,   42,   43,    0,   42,   43,    0,   44,   28,
       28,   44,   45,   29,   46,   45,   47,   46,   49,   47,
       41,   49,    0,    0,    0,   42,   43,   43,    0,   29,
        0,   44,   42,   48,    0,   45,   48,   46,   45,   47,
       50,   49,   44,   50,   47,    0,   51,   44,   44,   51,
        0,    0,   53,   49,   46,   53,   48,   48,   52,   54,
        0,   52,   54,   50,    0,   55,    0,   50,   55,   51,
        0,   58,    0,   59,   58,   53,   59,   60,   51,    0,

       60,   52,   54,    0,   52,    0,   53,   61,   55,   55,
       61,    0,   62,   54,   58,   62,   59,    0,   63,    0,
       60,   63,    0,   60,   60,   59,   58,    0,   65,   64,
       61,   65,   64,   66,   67,   62,   66,   67,    0,    0,
        0,   63,   64,   64,   68,   64,   69,   68,    0,   69,
       70,   65,   64,   70,    0,   71,   66,   67,   71,    0,
       72,   73,   65,   72,   73,   66,    0,   68,   74,   69,
        0,   74,   76,   70,   67,   76,   69,   75,   71,   68,
       75,    0,   77,   72,   73,   77,   78,   79,    0,   78,
       79,   74,    0,   73,   81,   76,   76,   81,   80,    0,

       75,   80,   74,   84,    0,   77,   84,   75,   82,   78,
       79,   82,   77,   83,    0,    0,   83,   81,    0,    0,
        0,   80,   79,    0,   85,   86,   84,   85,   86,   78,
        0,   82,    0,   80,   81,    0,   83,    0,   82,    0,
       83,    0,   87,   84,   83,   87,   88,   85,   86,   88,
        0,   85,    0,   89,   87,   86,   89,   87,   90,   87,
       91,   90,    0,   91,   93,   87,    0,   93,   92,   88,
        0,   92,   94,   88,    0,   94,   89,   95,    0,   96,
       95,   90,   96,   91,   90,   97,   98,   93,   97,   98,
        0,   92,    0,   89,    0,   94,   91,   92,   99,   93,

       95,   99,   96,  100,   95,    0,  100,    0,   97,   98,
       94,    0,  101,  102,   96,  101,  102,  103,    0,    0,
      103,   99,   99,    0,  106,    0,  100,  106,  104,    0,
      100,  104,    0,    0,  105,  101,  102,  105,  107,    0,
      103,  107,  108,  109,  101,  108,  109,  106,  102,    0,
      110,  104,  104,  110,  106,  103,  111,  105,    0,  111,
        0,  107,  105,    0,  112,  108,  109,  112,  113,  114,
        0,  113,  114,  110,  110,  115,    0,    0,  115,  111,
      111,    0,  116,  109,    0,  116,    0,  112,    0,    0,
        0,  113,  114,  114,  117,    0,  118,  117,  115,  118,

      119,    0,    0,  119,  112,  116,    0,    0,  120,  116,
      115,  120,  121,  122,    0,  121,  122,  117,  117,  118,
        0,  123,  124,  119,  123,  124,  125,  126,    0,  125,
      126,  120,    0,    0,  119,  121,  122,  127,  128,  129,
      127,  128,  129,  120,  123,  124,    0,    0,  130,  125,
      126,  130,  122,  131,  132,    0,  131,  132,    0,    0,
      127,  128,  129,  129,  126,  127,  133,  134,    0,  133,
      134,  130,    0,    0,    0,    0,  131,  132,  128,    0,
      135,  136,  130,  135,  136,  137,    0,    0,  137,  133,
      134,  134,    0,  138,  139,  132,  138,  139,  133,  140,

        0,    0,  140,  135,  136,    0,  135,  141,  137,  142,
      141,  143,  142,  137,  143,  144,  138,  139,  144,    0,
      145,  146,  140,  145,  146,    0,    0,  139,  138,  140,
      141,    0,  142,  147,  143,    0,  147,  149,  144,  148,
      149,  143,  148,  145,  146,    0,  150,    0,  145,  150,
      144,    0,    0,    0,    0,  146,  147,    0,  148,    0,
      149,  151,  148,  152,  151,  153,  152,  147,  153,  150,
      154,    0,  155,  154,  150,  155,  156,  149,  157,  156,
      158,  157,  159,  158,  151,  159,  152,    0,  153,  152,
        0,    0,    0,  154,    0,  155,  151,    0,    0,  156,

        0,  157,    0,  158,    0,  159,  157,  155,    0,    0,
      154,    0,    0,    0,  156,    0,    0,    0,    0,  158,
      161,    0,  161,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Rachas.l"
#define INITIAL 0
#line 4 "Rachas.l"
#include "y.tab.h"
void yyerror (char *s);
int yylex();
char* textValor();


#line 633 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 28 "Rachas.l"

#line 786 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 161 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 724 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 29 "Rachas.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 30 "Rachas.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 31 "Rachas.l"
{}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "Rachas.l"
{return VSALIDA;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 33 "Rachas.l"
{return MSALIDA;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 34 "Rachas.l"
{return SALIDA;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 35 "Rachas.l"
{return BSALIDA;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 36 "Rachas.l"
{return SIN;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 37 "Rachas.l"
{return COS;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 38 "Rachas.l"
{return TAN;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 39 "Rachas.l"
{return COT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 40 "Rachas.l"
{return SEC;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 41 "Rachas.l"
{return CSC;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 42 "Rachas.l"
{return GETROOT;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 43 "Rachas.l"
{return GETEXP;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 44 "Rachas.l"
{return GETLOG;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 45 "Rachas.l"
{return NPP;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 46 "Rachas.l"
{return NIP;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 47 "Rachas.l"
{return NPJ;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 48 "Rachas.l"
{return CONCATENACIONVECTORES;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 49 "Rachas.l"
{return UNIONTRATAMIENTO;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 50 "Rachas.l"
{return UNIONBLOQUE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 51 "Rachas.l"
{return UNIONMODELO;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 57 "Rachas.l"
{return MIENTRAS;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 58 "Rachas.l"
{return CONDICION;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 59 "Rachas.l"
{return ASIGNACION;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 60 "Rachas.l"
{yylval.numberI = atoi(yytext); return NUMERO_ENTERO;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 61 "Rachas.l"
{yylval.numberF = atof(yytext); return NUMERO_FLOTANTE;} 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 62 "Rachas.l"
{yylval.str = textValor(); return ID;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 63 "Rachas.l"
{return yytext[0];}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 64 "Rachas.l"
{yylval.str = textValor(); return LOGICA;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 65 "Rachas.l"
{return PARENTESISA;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 66 "Rachas.l"
{return PARENTESISB;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 67 "Rachas.l"
{return CORCHETEA;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 68 "Rachas.l"
{return CORCHETEB;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 69 "Rachas.l"
{return LLAVESA;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 70 "Rachas.l"
{return LLAVESB;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 71 "Rachas.l"
{return PA;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 72 "Rachas.l"
{return PB;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 73 "Rachas.l"
{return OR;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 74 "Rachas.l"
{ECHO; yyerror ("unexpected character");}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 76 "Rachas.l"
ECHO;
	YY_BREAK
#line 1087 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 161 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 161 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 160);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 76 "Rachas.l"


char* textValor(){
    char* palabra = (char*) malloc(sizeof(char)*yyleng);
    snprintf(palabra, yyleng+1, "%s", yytext);
    return palabra;
}

int yywrap (void) {
    return 1;
}
